### ISSUE TITLE
Refactoring `write_enum_type_defs` for improved readability and brevity

### ISSUE THREAD

**Issue by arabacibahadir** [microsoft/datagenDV#1]
The `write_enum_type_defs` function in the current implementation is functional, but it can be improved for better readability and maintainability.
To achieve this, I propose using `f-strings` and `join()` to create the C type definition string in a more concise and readable manner. 
I would like to open a pull request to implement these changes, and I would appreciate any feedback or suggestions regarding the proposed changes.

**Comment by qzcx** [comment]
Thanks for the contribution.
Looked at your PR. 
Agreed it could be better. 
I based this file off of existing code written ages ago and copied the style at the time instead of rewriting it.
My gut reaction is that we should apply the same changes to the other two write_* functions. 

I need to do some thinking about some of the style and directives of the generated C code for the typical user.

**Comment by qzcx** [comment]
Don't really consider this "issue worthy" since it is unneeded refactoring so I'm going to close it. Will consider applying these changes or similar next time I have a reason to change this file.
